# -*- coding: utf-8 -*-
"""Curneu task : 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GNHZnGfN0SAWlp4_QfA28HMjAQWoc5am

**Dataset upload**
"""

from google.colab import files 
uploaded = files.upload()

import pandas as pd 
import io 
fruits = pd.read_csv(io.BytesIO(uploaded['fruits.csv'])) 
fruits.head()

"""**Data preprocessing**"""

predct = dict(zip(fruits.fruit_label.unique(), fruits.fruit_name.unique()))   
predct

#checking how many unique fruit names are present in the dataset
fruits['fruit_name'].value_counts()

apple_data=fruits[fruits['fruit_name']=='apple']
orange_data=fruits[fruits['fruit_name']=='orange']
lemon_data=fruits[fruits['fruit_name']=='lemon']
mandarin_data=fruits[fruits['fruit_name']=='mandarin']

apple_data.head()

mandarin_data.head()

orange_data.head()

lemon_data.head()

"""**Data visualization and feature engineering**"""

import matplotlib.pyplot as plt
plt.scatter(fruits['width'],fruits['height'])

plt.scatter(fruits['mass'],fruits['color_score'])

plt.plot(fruits['height'],label='Height')
plt.plot(fruits['width'],label='Width')
plt.legend()

"""**Splitting of dataset**"""

from sklearn.model_selection import train_test_split
X=fruits[['mass','width','height']]
Y=fruits['fruit_label']
X_train,X_test,y_train,y_test=train_test_split(X,Y,random_state=0)

X_train.describe()

X_test.describe()

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)

knn.score(X_test,y_test)

#parameters of following function are mass,width and height
#Case 1
prediction1=knn.predict([['100','6.3','8']])
predct[prediction1[0]]

#Case 2
prediction2=knn.predict([['300','7','10']])
predct[prediction2[0]]

#Case 3
prediction3=knn.predict([['150','8','15']])
predct[prediction3[0]]